apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secrets"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.name }}"
    component: "{{ .Values.component }}"
    tier: "{{ .Values.tier }}"
    environment: "{{ .Values.environment }}"
    {{- include "common.labels" . | nindent 8 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
