apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.name }}"
    component: "{{ .Values.component }}"
    tier: "{{ .Values.tier }}"
    environment: "{{ .Values.environment }}"
    {{- include "common.labels" . | nindent 8 }}
spec:
  selector:
    app: "{{ .Values.name }}"
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
    name: http
  type: ClusterIP
