# <!-- Powered by BMAD™ Core -->
# BMAD Core Configuration - Hybrid Integration
# This bridges standard BMAD with our custom cflow platform

markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad

# Custom cflow Platform Integration
cflow:
  enabled: true
  mcp_tools: true
  supabase_integration: true
  multi_user_cluster: true
  hil_system: true
  
# Project Configuration
project:
  name: "cflow-platform"
  type: "fullstack"
  domain: "ai-platform"
  complexity: "high"
  multi_user: true
  cluster_deployment: true

# Agent Configuration
agents:
  enabled:
    - bmad-master
    - analyst
    - pm
    - architect
    - po
    - sm
    - dev
    - qa
    - ux-expert

# Workflow Configuration
workflows:
  default: "brownfield-fullstack"
  available:
    - brownfield-fullstack
    - brownfield-service
    - brownfield-ui
    - greenfield-fullstack
    - greenfield-service
    - greenfield-ui

# HIL Configuration - Enhanced with our custom system
hil:
  enabled: true
  interactive_mode: true
  elicitation_required: true
  workflow_pausing: true
  database_sessions: true
  multi_user_support: true

# Integration Configuration
integrations:
  cursor: true
  mcp: true
  cerebral: true
  supabase: true
  custom_hil: true
  expansion_packs: true