apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: bmad-api-production
    component: api
    environment: production
    tier: backend
  name: bmad-api-monitor
  namespace: cerebral-production
spec:
  endpoints:
  - interval: 30s
    path: /bmad/metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app: bmad-api-production
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bmad-api-production
    component: api
    environment: production
    tier: backend
  name: bmad-api-metrics
  namespace: cerebral-production
spec:
  ports:
  - name: metrics
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: bmad-api-production
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: bmad-api-production
    component: api
    environment: production
    tier: backend
  name: bmad-api-alerts
  namespace: cerebral-production
spec:
  groups:
  - name: bmad-api.rules
    rules:
    - alert: BMADAPIDown
      annotations:
        description: 'BMAD API service has been down for more than 5 minutes.'
        summary: 'BMAD API service is down'
      expr: up{job="bmad-api-production"} == 0
      for: 5m
      labels:
        severity: critical
    
    - alert: BMADAPIHighErrorRate
      annotations:
        description: 'BMAD API error rate is above 5% for more than 5 minutes.'
        summary: 'BMAD API high error rate'
      expr: rate(bmad_api_errors_total[5m]) / rate(bmad_api_requests_total[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
    
    - alert: BMADAPIHighResponseTime
      annotations:
        description: 'BMAD API average response time is above 2 seconds for more than 5 minutes.'
        summary: 'BMAD API high response time'
      expr: histogram_quantile(0.95, rate(bmad_api_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
    
    - alert: BMADAPIHighCPUUsage
      annotations:
        description: 'BMAD API CPU usage is above 80% for more than 10 minutes.'
        summary: 'BMAD API high CPU usage'
      expr: rate(container_cpu_usage_seconds_total{pod=~"bmad-api-production-.*"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
    
    - alert: BMADAPIHighMemoryUsage
      annotations:
        description: 'BMAD API memory usage is above 90% for more than 10 minutes.'
        summary: 'BMAD API high memory usage'
      expr: container_memory_usage_bytes{pod=~"bmad-api-production-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 10m
      labels:
        severity: warning
    
    - alert: BMADAPIWorkflowFailures
      annotations:
        description: 'BMAD workflow failure rate is above 10% for more than 5 minutes.'
        summary: 'BMAD API workflow failures'
      expr: rate(bmad_workflow_failures_total[5m]) / rate(bmad_workflow_executions_total[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
    
    - alert: BMADAPIDatabaseConnectionIssues
      annotations:
        description: 'BMAD API database connection failures are above 5 per minute for more than 5 minutes.'
        summary: 'BMAD API database connection issues'
      expr: rate(bmad_database_connection_failures_total[5m]) > 5
      for: 5m
      labels:
        severity: critical
    
    - alert: BMADAPIExpansionPackIssues
      annotations:
        description: 'BMAD expansion pack installation failures are above 3 per minute for more than 5 minutes.'
        summary: 'BMAD API expansion pack issues'
      expr: rate(bmad_expansion_pack_failures_total[5m]) > 3
      for: 5m
      labels:
        severity: warning
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: bmad-api-production
    component: monitoring
    environment: production
    tier: backend
  name: bmad-api-dashboard
  namespace: cerebral-production
data:
  dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "BMAD API Production Dashboard",
        "tags": ["bmad", "api", "production"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "BMAD API Health Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"bmad-api-production\"}",
                "legendFormat": "API Status"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "mappings": [
                  {
                    "options": {
                      "0": {
                        "text": "DOWN"
                      },
                      "1": {
                        "text": "UP"
                      }
                    },
                    "type": "value"
                  }
                ],
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {
                      "color": "red",
                      "value": 0
                    },
                    {
                      "color": "green",
                      "value": 1
                    }
                  ]
                }
              }
            },
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(bmad_api_requests_total[5m])",
                "legendFormat": "Requests/sec"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 6,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(bmad_api_errors_total[5m]) / rate(bmad_api_requests_total[5m]) * 100",
                "legendFormat": "Error Rate %"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 18,
              "y": 0
            }
          },
          {
            "id": 4,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(bmad_api_request_duration_seconds_bucket[5m]))",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(bmad_api_request_duration_seconds_bucket[5m]))",
                "legendFormat": "50th percentile"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            }
          },
          {
            "id": 5,
            "title": "CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"bmad-api-production-.*\"}[5m]) * 100",
                "legendFormat": "CPU Usage %"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 12,
              "y": 8
            }
          },
          {
            "id": 6,
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{pod=~\"bmad-api-production-.*\"} / 1024 / 1024",
                "legendFormat": "Memory Usage MB"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 6,
              "x": 18,
              "y": 8
            }
          },
          {
            "id": 7,
            "title": "Workflow Executions",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(bmad_workflow_executions_total[5m])",
                "legendFormat": "Workflows/sec"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 16
            }
          },
          {
            "id": 8,
            "title": "Expansion Pack Activity",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(bmad_expansion_pack_installs_total[5m])",
                "legendFormat": "Installs/sec"
              },
              {
                "expr": "rate(bmad_expansion_pack_activations_total[5m])",
                "legendFormat": "Activations/sec"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 16
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
