name: Build and Push WebMCP Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'cflow_platform/core/webmcp_server.py'
      - 'cflow_platform/core/**'
      - 'infrastructure/docker/Dockerfile.webmcp'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'cflow_platform/core/webmcp_server.py'
      - 'cflow_platform/core/**'
      - 'infrastructure/docker/Dockerfile.webmcp'
      - 'pyproject.toml'
      - 'uv.lock'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: baerautotech/cflow-platform-webmcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: infrastructure/docker/Dockerfile.webmcp
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    - name: Generate SHA256 digest
      id: digest
      run: |
        # Get the SHA256 digest of the latest image
        DIGEST=$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --format='{{index .RepoDigests 0}}' | cut -d'@' -f2)
        echo "digest=$DIGEST" >> $GITHUB_OUTPUT
        echo "SHA256 digest: $DIGEST"

    - name: Update deployment with SHA256 digest
      if: github.ref == 'refs/heads/main'
      run: |
        # Update the deployment file with the SHA256 digest
        sed -i "s|ghcr.io/baerautotech/cflow-platform-webmcp:latest|ghcr.io/baerautotech/cflow-platform-webmcp@sha256:${{ steps.digest.outputs.digest }}|g" infrastructure/kubernetes/webmcp-cerebral-development.yaml
        
        # Commit and push the updated deployment
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add infrastructure/kubernetes/webmcp-cerebral-development.yaml
        git diff --staged --quiet || git commit -m "Update webmcp deployment with SHA256 digest: ${{ steps.digest.outputs.digest }}"
        git push
